"use client";
import { Member } from "./MemberExplorer";

export const MEMBERS: Member[] = [
  {
    name: "Ekaterina Atanasov",
    team: "Electronics",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Vivien Hopf",
    team: "Neuromotion",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Niels Thiemann",
    team: "BCI",
    status: "Member",
    studyCourse: "MSc Neuroengineering",
  },
  {
    name: "Watsa Jukthumrong",
    team: "Electronics",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Glykeria Rovatsou",
    team: "Operations",
    status: "Board Member & Co-Director",
    studyCourse: undefined,
  },
  {
    name: "Jens von Greiff",
    team: "BCI",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Manuel Methasani",
    team: "BCI",
    status: "Passive Member",
    studyCourse: undefined,
  },
  {
    name: "Nicolas Mallinckrodt",
    team: "Operations",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Iustin Curcean",
    team: "BCI",
    status: "Passive Member",
    studyCourse: "-",
  },
  {
    name: "Iustin Curcean",
    team: "Operations",
    status: "Passive Member",
    studyCourse: "-",
  },
  {
    name: "Levi Frim",
    team: "BCI",
    status: "Member",
    studyCourse: "-",
  },
  {
    name: "Nick Breit",
    team: "Operations",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Jenny Tabeling",
    team: "Operations",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Ekaterina Semenova",
    team: "Neuromotion",
    status: "Team Lead",
    studyCourse: undefined,
  },
  {
    name: "Rania Bannour",
    team: "Electronics",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Sadat",
    team: "BCI",
    status: "Team Lead",
    studyCourse: "-",
  },
  {
    name: "Lucas Mateus Martins Araújo e Castro",
    team: "BCI",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Marina Tazeva",
    team: "Operations",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Anita Reutova",
    team: "Operations",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Muhammed Samir Öztürk",
    team: "Operations",
    status: "Passive Member",
    studyCourse: undefined,
  },
  {
    name: "Enrico Fazzi",
    team: "Electronics",
    status: "Team Lead",
    studyCourse: undefined,
  },
  {
    name: "Paolo Favero",
    team: "BCI",
    status: "Advisor Member",
    studyCourse: undefined,
  },
  {
    name: "Ioana Milea",
    team: "Electronics",
    status: "Passive Member",
    studyCourse: undefined,
  },
  {
    name: "Nele Wunner",
    team: "Operations",
    status: "Team Lead",
    studyCourse: undefined,
  },
  {
    name: "Isabel Tscherniak",
    team: "BCI",
    status: "Board Member & Co-Director",
    studyCourse: "M.Sc. Neuroengineering",
  },
  {
    name: "Anna Cernina",
    team: "Electronics",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Tobias Konieczny",
    team: "OpenHardware",
    status: "Passive Member",
    studyCourse: undefined,
  },
  {
    name: "Daniel",
    team: "BCI",
    status: "Board Member & Co-Director",
    studyCourse: undefined,
  },
  {
    name: "Delfina",
    team: "BCI",
    status: "Advisor Member",
    studyCourse: undefined,
  },
  {
    name: "Elizabeth Emery",
    team: "Operations",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Ana McWhinnie Fernandez",
    team: "BCI",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Mert Önder",
    team: "Neuromotion",
    status: "Member",
    studyCourse: undefined,
  },
  {
    name: "Doğa",
    team: "Operations",
    status: "Passive Member",
    studyCourse: undefined,
  },
  {
    name: "Thien Le",
    team: "BCI",
    status: "Advisor Member",
    studyCourse: "phD student at Medical University Vienna",
  },
  {
    name: "Thien Le",
    team: "Neuromotion",
    status: "Advisor Member",
    studyCourse: "phD student at Medical University Vienna",
  },
  {
    name: "Fauzi Sholichin",
    team: "Operations",
    status: "Member",
    studyCourse: "M. Eng, AI Engineering of Autonomous Systems",
  },
  {
    name: "Pietro Marcolongo",
    team: "BCI",
    status: "Member",
    studyCourse: "M.Sc. Bioengineering for Neuroscience",
  },
  {
    name: "Dora Pruteanu",
    team: "BCI",
    status: "Member",
    studyCourse: "M. Sc. Computer Science",
  },
  {
    name: "Esther Utasá",
    team: "Neuromotion",
    status: "Member",
    studyCourse: "M. Sc. Neuroengineering",
  },
  {
    name: "Alexandra Khan",
    team: "Operations",
    status: "Member",
    studyCourse: "B. Sc. Bioinformatics",
  },
  {
    name: "Cristoph Müthering",
    team: "Operations",
    status: "Member",
    studyCourse: "M. Sc. Biochemistry",
  },
  {
    name: "Christian Ritter",
    team: "Neuromotion",
    status: "Member",
    studyCourse: "M. Sc. Neuroengineering",
  },
  {
    name: "Carl Ziesemer",
    team: "Neuromotion",
    status: "Member",
    studyCourse: "B. Sc. Management & Technology",
  },
  {
    name: "Jorge García Mosquera",
    team: "Electronics",
    status: "Member",
    studyCourse: "M. Sc. Neuroengineering",
  },
  {
    name: "Sining Li",
    team: "Operations",
    status: "Member",
    studyCourse: "M. A. Cultural & Cognitive Linguistics",
  },
  {
    name: "Ahmed Ghaleb",
    team: "Neuromotion",
    status: "Member",
    studyCourse: "M. Sc. Electrical Engineering",
  },
  {
    name: "Jan Vizthum",
    team: "Neuromotion",
    status: "Member",
    studyCourse: "B.Sc., Engineering Science",
  },
  {
    name: "Katalin Czopf",
    team: "BCI",
    status: "Member",
    studyCourse: "M. Sc. Biomedical Engineering & Medical Physics",
  },
  {
    name: "Begüm Ayaz",
    team: "BCI",
    status: "Member",
    studyCourse: "B. Sc. Molekular Biotechnology",
  },
  {
    name: "Gabriel Cabrera",
    team: "BCI",
    status: "Member",
    studyCourse: "B. Sc. Electrical and Computer Engineering",
  },
  {
    name: "Philipp Wagner",
    team: "Neuromotion",
    status: "Member",
    studyCourse: "M.Sc. Robotics, Cognition, Intelligence",
  },
  {
    name: "Glenn Krafczyk",
    team: "BCI",
    status: "Member",
    studyCourse: "M.Sc. Mathematics",
  },
  {
    name: "Solmaz Hüseynli",
    team: "Operations",
    status: "Member",
    studyCourse: "B. Sc. Molecular Biotechnology",
  },
  {
    name: "Sara Gorriz",
    team: "BCI",
    status: "Member",
    studyCourse: "M.Sc. Neuroengineering",
  },
  {
    name: "Tuna Öztürk",
    team: "Electronics",
    status: "Member",
    studyCourse: "B. Sc. Electrical engineering & information technology",
  },
];
